### ISSUE TITLE
Aliens indexed 2 & 4 won't die

### ISSUE THREAD

**Issue by niwhsa9** [niwhsa9/Space-War#1]
When aliens are created, they are indexed (starting at 0 of course) and placed into an array. When hit by a player's missile, the array.splice(index, 1) command is used to remove the alien. Aliens are drawn by looping through the array and drawing the contents. Therefore, the alien should disappear when hit.  I know the hit-detection is working correctly due to console.log statements. Everything works fine for aliens 0,1, and 3. However, for aliens 2 & 4 (even numbers may have something to do with it?) when a missile hits, the hit is registered, but the aliens are still being drawn (and possibly not being removed from array)

**Comment by vihanb** [comment]
What does the debugger show when splicing?

**Comment by niwhsa9** [comment]
Will try it now downgoat

**Comment by niwhsa9** [comment]
problem was indexes changing, closing this, but issue still here.
